import AuthProvider from '@/components/providers/AuthProvider';
import { Providers } from '@/components/providers/ProviderNextUI';
import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';
import './globals.css';

const font = Work_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html
        lang="en"
        suppressHydrationWarning
        className="dark">
        <body className={font.className}>
          <Providers>{children}</Providers>
        </body>
      </html>
    </AuthProvider>
  );
}
